---
# Concourse CI/CD Pipeline for sample-dagster
# This pipeline builds, tests, and pushes Docker images to the registry

resources:
  # Git repository resource
  - name: repo
    type: git
    icon: github
    source:
      uri: git@github.com:singh-gur/sample-dagster.git
      branch: main
      private_key: ((github_private_key))

  # Docker image resource for pushing
  - name: docker-image
    type: registry-image
    icon: docker
    source:
      repository: regv2.gsingh.io/personal/sample-dagster
      username: ((registry_username))
      password: ((registry_password))
      tag: latest

  # Docker image with specific tag (commit SHA)
  - name: docker-image-tagged
    type: registry-image
    icon: docker
    source:
      repository: regv2.gsingh.io/personal/sample-dagster
      username: ((registry_username))
      password: ((registry_password))

jobs:
  # ============================================================================
  # Job: Test
  # Runs linting and tests before building
  # ============================================================================
  - name: test
    public: true
    plan:
      - get: repo
        trigger: true

      - task: lint-and-test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
              tag: "3.13-slim"

          inputs:
            - name: repo

          caches:
            - path: repo/.venv

          run:
            path: bash
            args:
              - -euc
              - |
                cd repo
                
                # Install uv for dependency management
                pip install --no-cache-dir uv
                
                # Install dependencies
                uv sync
                
                # Run linter
                echo "Running ruff check..."
                uv run ruff check .
                
                # Run formatter check
                echo "Running ruff format check..."
                uv run ruff format --check .
                
                # Run tests (if they exist)
                if [ -d "tests" ]; then
                  echo "Running tests..."
                  uv run pytest --cov || true
                fi
                
                echo "✅ All checks passed!"

  # ============================================================================
  # Job: Build and Push
  # Builds Docker image and pushes to registry
  # ============================================================================
  - name: build-and-push
    public: true
    plan:
      - get: repo
        trigger: true
        passed: [test]

      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
              tag: latest

          inputs:
            - name: repo

          outputs:
            - name: image

          params:
            CONTEXT: repo
            DOCKERFILE: repo/Dockerfile
            BUILD_ARGS_FILE: repo/ci/build-args.txt

          run:
            path: build

      - put: docker-image
        params:
          image: image/image.tar
          additional_tags: repo/.git/short_ref

      - put: docker-image-tagged
        params:
          image: image/image.tar
          additional_tags: repo/.git/ref

  # ============================================================================
  # Job: Build and Push (Tag-based releases)
  # Triggered only on git tags for versioned releases
  # ============================================================================
  - name: release
    public: true
    plan:
      - get: repo
        trigger: false

      - task: verify-tag
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine/git
              tag: latest

          inputs:
            - name: repo

          run:
            path: sh
            args:
              - -euc
              - |
                cd repo
                
                # Check if current commit has a tag
                TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")
                
                if [ -z "$TAG" ]; then
                  echo "❌ No tag found on current commit"
                  exit 1
                fi
                
                echo "✅ Found tag: $TAG"
                echo "$TAG" > ../tag-name

          outputs:
            - name: tag-name

      - task: build-release-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
              tag: latest

          inputs:
            - name: repo
            - name: tag-name

          outputs:
            - name: image

          params:
            CONTEXT: repo
            DOCKERFILE: repo/Dockerfile

          run:
            path: build

      - put: docker-image-tagged
        params:
          image: image/image.tar
          additional_tags: tag-name/tag-name

  # ============================================================================
  # Job: Security Scan
  # Scans Docker image for vulnerabilities
  # ============================================================================
  - name: security-scan
    public: true
    plan:
      - get: repo
        trigger: true
        passed: [build-and-push]

      - get: docker-image
        trigger: true
        passed: [build-and-push]

      - task: trivy-scan
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: aquasec/trivy
              tag: latest

          inputs:
            - name: repo

          params:
            IMAGE: regv2.gsingh.io/personal/sample-dagster:latest
            REGISTRY_USERNAME: ((registry_username))
            REGISTRY_PASSWORD: ((registry_password))

          run:
            path: sh
            args:
              - -euc
              - |
                echo "Scanning image: $IMAGE"
                
                # Login to registry
                trivy registry login regv2.gsingh.io \
                  --username "$REGISTRY_USERNAME" \
                  --password "$REGISTRY_PASSWORD"
                
                # Scan image for vulnerabilities
                trivy image \
                  --severity HIGH,CRITICAL \
                  --exit-code 0 \
                  --no-progress \
                  "$IMAGE"
                
                echo "✅ Security scan complete"

# ============================================================================
# Groups for organizing jobs in the UI
# ============================================================================
groups:
  - name: main
    jobs:
      - test
      - build-and-push
      - security-scan

  - name: release
    jobs:
      - release
